### PR TITLE
Use cmdliner

### PR DESCRIPTION
**Pull request by fxfactorial**
Implement replacement of Arg with cmdliner while passing all tests for `refmt_imp` along with some style changes.

@jordwalke You'll probably want to commit on top of this to replace the proper description in the man page's main `DESCRIPTION`.

### CODE REVIEW

**Comment by yunxing** [comment]
Hi @fxfactorial, I see there is still an outstanding comment. Do you want us to commandeer this diff if you are busy? 

Thanks for contributing, btw!

**Comment by fxfactorial** [comment]
@yunxing 

I'm trying to fix it but there's an issue with the tests not reading the input correctly, aka some areas of tests use `$FOO` instead of `"$FOO"`. Somehow its affecting it.

What do you mean commandeer, mean try to fix it yourself?

**Comment by yunxing** [comment]
@fxfactorial Ah thanks for pointing out. My bash-fu is too low. I will fix it. 

Commandeering means to push more diffs on top of yours by myself. Sometimes I feel bad when people have to resolve merge conflicts because of me reviewing diff too slow. In those cases I offer to do the rebasing for them.

**Comment by fxfactorial** [comment]
Sadly this wasn't merged in time and now the merge conflicts are too painful for me to fix.

**Comment by jordwalke** [comment]
Sorry about this @fxfactorial. At the time you wrote this, our dependency story was a nightmare. But now, we have `npm` build support which works with network-disconnected CI build servers -  we can easily make an npm package for cmdliner, and then it will just work on the CI servers.

**Comment by chenglou** [comment]
Btw let's be careful about including a dependency for a few flags in refmt. cc @bobzhang

**Comment by yunxing** [comment]
What's the tradeoff here? cmdliner has only one file.

**Comment by tekknolagi** [comment]
Because it's preeeettttyyyy

screenshot 2017-01-19 17 19 02

**Comment by fxfactorial** [comment]
Is that a picture of the build for my pr?

Sad wasn't merged.

**Comment by tekknolagi** [comment]
@fxfactorial No -- that is a picture of the build from my PR, which takes your PR and adopts it to current master.

**Comment by tekknolagi** [comment]
(Fixing merge conflicts, etc)

**Comment by fxfactorial** [comment]
Oh nice, the merge conflicts were too annoying for me to fix, glad you got it done 💯

**Comment by bobzhang** [comment]
I expect refmt is not a client facing tool

**Pull request closed without merging**
