### PR TITLE
Enable --add-printers in reasonbuild

### PR DESCRIPTION
**Pull request by tekknolagi**
This will create printers for user-defined types by default.

### CODE REVIEW

**Comment by yunxing** [comment]
@tekknolagi Do you think we should make this as a default behavior, or do you think we should make this as an option and make it default once we think this is stable enough?

**Comment by tekknolagi** [comment]
@yunxing Fair point. What's the best way to make this an option?

**Comment by yunxing** [comment]
@tekknolagi We don't control ocamlbuild so I don't think we can add a command line option to it. Maybe here we can use a environment variable? 

This will be temporary for people to try out before we switch this into a default behavior so I'm not too worried about it.

**Comment by jordwalke** [comment]
Would it be reasonable to have an extra entrypiont `rebuildwithprint` while we test it out?

**Comment by yunxing** [comment]
@jordwalke Implementation-wise, reusing the same command would be much easier.

**Comment by tekknolagi** [comment]
Environment variable is kind of gross but if it's *definitely* only temporary then I can do that.

**Comment by hcarty** [comment]
Since this is based on ocamlbuild using a tag might make sense.  That would make it easy for users to apply the flag per-file.

Also, if there's a generic feature here which is generally useful in ocamlbuild Gabriel Scherer is usually very open to PRs for the project.

**Comment by tekknolagi** [comment]
@hcarty What do you mean exactly?

**Comment by hcarty** [comment]
ocamlbuild uses tags, either specified on the command line, in a `_tags` file or `myocamlbuild.ml`, to specify most compilation flags.  It's possible (and somewhat common) to specify custom tags.

So a user could have a tags file which says:
```
true: add_type_printers
```
to add `show_*` functions for all of their types in all of their files, for example.  Or:
```
src/lib.re: add_type_printers
```
to only add printers for the types in `src/lib.re`.

Some documentation is available: https://github.com/ocaml/ocamlbuild/blob/master/manual/manual.adoc#tags-and-the-code-_tags-code-file and https://github.com/ocaml/ocamlbuild/blob/master/manual/manual.adoc#flag-declarations - the rest of the ocamlbuild manual may be helpful too.

For examples of tag implementations you can see https://github.com/ygrek/mybuild and https://github.com/hcarty/ocamlbuild-plugins.  https://github.com/hcarty/ocamlbuild-plugins/tree/master/tests/static is a relatively simple example of defining and using a new tag.

**Comment by tekknolagi** [comment]
Looks like right now the easiest non-PR way to do this would be to add the tag `pp(refmt --print binary --add-printers)` to files they want to add printers to.

**Comment by tekknolagi** [comment]
@hcarty @yunxing @jordwalke if anybody has feedback on how we might approach this with parametrized flags (ie `reason(add_printers ...)`), please let me know.

**Comment by tekknolagi** [comment]
@yunxing I think we can just ship as-is for now.

**Comment by yunxing** [comment]
This is good to merge. I don't think the CI is currently testing rebuild.

**Pull request merged**
