### PR TITLE
Add eval `opam config env`

### PR DESCRIPTION
**Pull request by SanderSpies**
I followed the installation instructions, but the rebuild command didn't work - but after running eval `opam config env` everything worked.

### CODE REVIEW

**Comment by yunxing** [comment]
Good catch. One does need to `eval opam config env` to make new opam configs take effects in the current shell. We should definitely put this instruction in the doc.

**Comment by chenglou** [comment]
The instruction to add `opam config env` is a few line above (in case you didn't see it)
(Hey again!)

**Comment by yunxing** [comment]
@chenglou I think we need to be explicit that people have to type it in the current shell.

**Comment by yunxing** [comment]
@SanderSpies Could you move the line right below `opam switch 4.02.3` ? If someone was using another switch before he switched to `4.02.3`, the package pinned below will be pinned to the original switch instead of `4.02.3` unless he types `eval opam config env`.

**Comment by SanderSpies** [comment]
@yunxing Will do.

@chenglou (Hey!) Right, my mistake indeed.

**Pull request merged**
