### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by yunxing**
Remove last call site of Str.

### CODE REVIEW

**Comment by yunxing** [comment]
Let's wait for the CI build to complete.

**Comment by SanderSpies** [comment]
Thanks, just stumbled upon this for the JSX branch.

**Comment by chenglou** [comment]
@yunxing I just merged #661. Can you rebase and see if things still make sense?

**Comment by yunxing** [comment]
@chenglou That diff should be good enough. Thanks. I will update this diff to remove unused code.

**Comment by yunxing** [comment]
Killed some dead code.

**Comment by chenglou** [comment]
Feel free to merge after the check.

**Pull request merged**
