### PR TITLE
Add missing final step of installation to README.md

### PR DESCRIPTION
**Pull request by jamesbrown0**
Add missing final step of installation

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by OvermindDL1** [comment]
For me anyway the 'opam pin' commands installed as well so the `opam install` step was superfluous.  Is this not the case everywhere?

**Comment by jamesbrown0** [comment]
That's not how it worked for me. I asked for help on Gitter, where it was pointed out that the packages weren't installed.

**Comment by jordwalke** [comment]
I think you might have been experiencing a different unrelated error. A few lines above, it installs a specific merlin extend (stable version that matches the others). Let me know if you think I should reopen this issue.

**Pull request closed without merging**
