### PR TITLE
Nested uncurrying + paren hugging

### PR DESCRIPTION
**Pull request by IwanKaramazow**
As @cristianoc pointed out, nested uncurrying should be possible:
```
add(. 2)(. 3);
```
now formats as
```
add(. 2, . 3);
```

Also adds test cases/support for uncurried syntax with "paren hugging":
```
f(. (1, 2));
f(. {
  a: "supersupersupersupersupersuperlong",
  b: "supersupersupersupersupersuperlong",
});
```

### CODE REVIEW

**Comment by chenglou** [comment]
Hummm, not sure we should support `add(. 2, . 3)`? Should we?

**Comment by IwanKaramazow** [comment]
Unfortunately, I think we should.
* The behaviour in master is a bug. I'd rather have the parser be "resilient" against this case.
* It's consistent with the formatting of `add(2)(3) -> add(2, 3)`
* It's consistent with types where we allow `type f = (int, . int) => unit` (but here it get's reformatted to `type f = int => (.int) => unit;`, unfortunately we don't have enough info at print time to do the same with expressions

**Comment by jordwalke** [comment]
I don't see this as a super common use case, so I'm happy to see anything that makes the implementation cleaner and/or more consistent.

**Comment by chenglou** [comment]
^ Sounds good then. Merging! Haven't corrected the outcome printer yet.

**Pull request merged**
