### PR TITLE
Re-enable 4.02.3 on Circle

### PR DESCRIPTION
**Pull request by tekknolagi**
This also adds support for 4.02.3-specific tests that are currently failing on
Travis CI.

### CODE REVIEW

**Comment by tekknolagi** [comment]
@yunxing let's merge this before https://github.com/facebook/reason/pull/1113

**Comment by tekknolagi** [comment]
Build is marked failing but there is another build going w/o cache that I expect to fully pass.

**Comment by tekknolagi** [comment]
Passed, pending @yunxing's fix

**Comment by yunxing** [comment]
Cool. Thanks!

**Pull request merged**
