### PR TITLE
Bring outcome printer up to date w/ the new syntax, fixes #1453

### LINKED ISSUE #1453: Fix outcome printer
The outcome printer hasn't been updated to reflect the syntax change. This is the last last issue we'd tackle before shipping it.

### PR DESCRIPTION
**Pull request by jaredly**
now prints
```
let x1: (unit) => int;
let x2: ('a) => int;
let x3: (int, 'a) => int;
let x4: (('a, 'b)) => int;
let x5: ('a, 'b) => int;
let x6: (~x: 'a, ~y: 'b) => int;
let x7: (~x: int, ~y: string) => int;
let x8: (~x: int=?, ~y: 'a=?, ~z: string=?, unit) => int;
type a = int;
type b = float;
type c = string;
type t1 = (a) => b;
type t2 = (a, b) => c;
type t3 = ((a, b)) => c;
type t4 = (~x: int, ~y: string) => c;
type t5 = (~x: a=?) => b;
type t6 = int;
type t7('a) = list('a);
type t8('a, 'b) = (list('a), 'b);
type t9 = t8 (string,  int);
class type restricted_point_type = { pub bump: unit; pub get_x: int };
class type t10 ('a) = { pub thing: 'a };
class type t11 ('a, 'b) = { pub thing: ('a, list('b)) };
module MyFirstModule: { let x: int; type i = int and n = string; };
module type HasTT = { type tt; };
module SubModule: HasTT;
module type HasEmbeddedHasTT = { module SubModuleThatHasTT = SubModule; };
module type HasPolyType = { type t('a); };
module type HasDoublePoly = { type m('b, 'c); };
module type HasDestructivelySubstitutedPolyType = {  };
module type HasDestructivelySubstitutedSubPolyModule =
  { module X: HasDestructivelySubstitutedPolyType; };
module type HasSubPolyModule = { module X: HasPolyType; };
module EmbedsSubPolyModule: HasSubPolyModule;
module InliningSig: { let x: int; let y: int; };
module MyFunctor:
  (M : HasTT) => { type reexportedTT = M.tt; let someValue: int; };
module MyFunctorResult: { type reexportedTT = string; let someValue: int; };
module type ASig = { let a: int; };
module type BSig = { let b: int; };
module CurriedSugar: (A : ASig) => (B : BSig) => { let result: int; };
type withThreeFields = { name: string, age: int, occupation: string, };
let testRecord: withThreeFields;
let makeRecordBase: (unit) => withThreeFields;
type t = A | B(int) | C(int, int) | D((int, int));
class aClass :
  ('a) =>
  {
    pub a1: int;
    pub a2: (unit) => int;
    pub a3: (int, int) => int;
    pub a4: (int, int) => int
  };
```

fixes #1453

### CODE REVIEW

**Comment by jaredly** [comment]
soo circleci's node is too old to run the tests I added :/

**Comment by chenglou** [comment]
Gotta write in vanilla es5 JS =)

**Comment by jordwalke** [comment]
Thoroughly impressed with how the Reason community is stepping up to get the next major version out quickly. Thank you, @jaredly.

**Comment by chenglou** [comment]
@jaredly updated node. Wanna try rebasing now? =D

**Pull request merged**
