### PR TITLE
WIP - ppx_export

### PR DESCRIPTION
**Pull request by SanderSpies**
Work in progress.

### CODE REVIEW

**Comment by hcarty** [comment]
Once this is ready, would you be willing to distribute it as a separate package in opam? I suspect that there would be interest from the OCaml community in general.

**Comment by SanderSpies** [comment]
@hcarty I think placing it under something like `reasonml/ppx_export` would make sense.

**Comment by yunxing** [comment]
Sorry, what does this do? Is there an issue talking about this?

**Comment by SanderSpies** [comment]
@yunxing This is related to: https://github.com/facebook/reason/issues/617 - the idea is basically to add an extension point that can later on be used by the `export` keyword.

Right now it changes
```
let%export int_implicit = 1
let%export string_implicit = "str"
let%export char_implicit = 'c'
let%export float_implicit = 1.1

let%export int_explicit:int = 1
let%export string_explicit:string = "str"
let%export char_explicit:char = 'c'
let%export float_explicit:float = 1.1

type%export foo = | Pleh | Bleh

let%export x:foo = Bleh

type%export record = {
  a: string
}

let%export impl:record = { a = "2"}

type extensible = ..

type%export extensible += | SayWhat

exception%export SomeException of string

[%%export [@@@foo]]

(* [%%export [%%export]] *)

let%export a (b:int) (c:char) : string = "boe"
```
into
```
include (struct let int_implicit = 1  end : sig val int_implicit : int end)
include
  (struct let string_implicit = "str"  end :
    sig val string_implicit : string end)
include
  (struct let char_implicit = 'c'  end : sig val char_implicit : char end)
include
  (struct let float_implicit = 1.1  end : sig val float_implicit : float end)
include
  (struct let int_explicit : int = 1  end : sig val int_explicit : int end)
include
  (struct let string_explicit : string = "str"  end :
    sig val string_explicit : string end)
include
  (struct let char_explicit : char = 'c'  end :
    sig val char_explicit : char end)
include
  (struct let float_explicit : float = 1.1  end :
    sig val float_explicit : float end)
include
  (struct type foo =
            | Pleh 
            | Bleh  end : sig type foo =
                                | Pleh 
                                | Bleh  end)
include (struct let x : foo = Bleh  end : sig val x : foo end)
include
  (struct type record = {
            a: string } end : sig type record = {
                                    a: string } end)
include
  (struct let impl : record = { a = "2" }  end : sig val impl : record end)
type extensible = ..
include
  (struct type extensible +=  
            | SayWhat  end : sig type extensible +=  
                                   | SayWhat  end)
include
  (struct exception SomeException of string  end :
    sig exception SomeException of string  end)
include (struct [@@@foo ] end : sig [@@@foo ] end)
include
  (struct let a (b : int) (c : char) = ("boe" : string)  end :
    sig val a : int -> char -> string end)
```

Still missing: modules, classes, and nested export structures.

**Comment by jaredly** [comment]
(I'm jumping in to work on this)

**Comment by jaredly** [comment]
continued over here https://github.com/facebook/reason/pull/1251

**Comment by SanderSpies** [comment]
Closes in favour of https://github.com/facebook/reason/pull/1251

**Pull request closed without merging**
