### PR TITLE
Add travis-ci config

### PR DESCRIPTION
**Pull request by tadeuzagallo**
Testing the configuration

### CODE REVIEW

**Comment by tadeuzagallo** [comment]
It works!

/cc @jordwalke

**Comment by yunxing** [comment]
Looks good, thanks!

**Comment by yunxing** [comment]
@tadeuzagallo hmm... how does this work? Do you need admin access to add authorize travis to access this repo?

**Comment by tadeuzagallo** [comment]
You need admin access to enable Travis for the repo. After that it should be fine. Is that what you mean?

**Comment by yunxing** [comment]
@tadeuzagallo Right. Was just wondering where in fb's internal system can one gets admin access to the repo. But we can discuss that offline.

**Pull request merged**
