### PR TITLE
Use stages and build matrix

### PR DESCRIPTION
**Pull request by ulrikstrid**

### CODE REVIEW

**Comment by ulrikstrid** [comment]
@jordwalke I think this is good to go if the UI works for you. I was having problems seeing any run for some reason

**Comment by jordwalke** [comment]
Any downside to landing this?

**Comment by ulrikstrid** [comment]
This is the more modern approach to azure pipelines and is a nice way of structuring the different parts. This will set us up better for creating releases on the future.
Using matrixes also makes it easier to see what is going to run from just looking at the yaml.
Personally I can't see any downsides, but I love new things and this is in "preview".

**Comment by sync** [comment]
Looking good 👍

**Pull request merged**
