### PR TITLE
I think this should fix unbound module Ast_404

### PR DESCRIPTION
**Pull request by tekknolagi**
I don't really know how OCaml works exactly, but my I think this fixes @rickyvetter's issue. @rickyvetter can you try on this branch and see if your issue is fixed?

### CODE REVIEW

**Comment by yunxing** [comment]
@tekknolagi Do we still need this? I think Ricky has fixed this on his side.

**Comment by rickyvetter** [comment]
Yeah I don't think this is needed. Closing since it's working on my end. Thanks for the help! :)

**Comment by jordwalke** [comment]
Thanks everyone. Mind explaining the fix for posterity

**Comment by tekknolagi** [comment]
@rickyvetter added ocaml-migrate-parsetree to his package.json, as far as I am aware.

**Comment by jordwalke** [comment]
Ah, that's what I thought would solve the problem. @yunxing Note that our theory was correct.

**Pull request closed without merging**
