### PR TITLE
(RDY) Parse correct locations extension expressions sugar

### PR DESCRIPTION
**Pull request by IwanKaramazow**
Fixes https://github.com/facebook/reason/issues/2143

### CODE REVIEW

**Comment by jordwalke** [comment]
You are awesome. Did you test via linking a local build of Reason?

**Comment by andreypopp** [comment]
I did test it on https://github.com/andreypopp/reason-ppx-let-merlin and seeing the same behaviour as previously. Did I missing something? `refmt` and `ocamlmerlin-reason` point to local builds.

**Comment by IwanKaramazow** [comment]
@jordwalke, using esy link to test this out locally
Still WIP, the locations under extension sugar need to be revised...

**Comment by IwanKaramazow** [comment]
@jordwalke this is ready.

Locations where missing in parts of the extension expression, resulting in Merlin have a very bad time.
Fixed all locations and streamlined the behaviour in terms of what the stock Ocaml parser does.

image

**Comment by andreypopp** [comment]
Just tested this and it works great! Autocomplete also started working for me (previously bindings introduced by `let%bind` weren't visible). Thank you @IwanKaramazow!

**Comment by jordwalke** [comment]
🎉 
Thanks, this was the main blocker for converting more of the esy codebase (parts that use async operations)
Thank you, as always.

**Comment by zindel** [comment]
This works like a charm within the fastpack codebase! Thank you so much, @IwanKaramazow, this makes a huge difference!

**Pull request merged**
