### PR TITLE
Ocp indent all the .ml files

### PR DESCRIPTION
**Pull request by SanderSpies**
Although not perfect, it ensures that the indentation is the same everywhere.

(What triggered this was:  https://github.com/facebook/reason/blob/master/src/reason_pprint_ast.ml#L3756)

Perhaps an idea to put this into the "Reason developer" workflow?

### CODE REVIEW

**Comment by SanderSpies** [comment]
(btw. I fully understand if this PR is too big)

**Comment by jordwalke** [comment]
We have some people with important outstanding PRs (such as 4.03 support). How would this effect their ability to git rebase?

**Comment by yunxing** [comment]
This is definitely helpful. 

Maybe it is easier to do it incrementally ?

**Comment by kayceesrk** [comment]
@jordwalke was going to redo the 4.03 support PR since we now use menhir so this particular commit will not affect it. But the PR is big, and might be worth doing incrementally.

**Comment by jordwalke** [comment]
Agree, @kayceesrk

**Comment by SanderSpies** [comment]
Alright, I'll be picking this up incrementally :+1:.

**Pull request closed without merging**
