### PR TITLE
Fixes #1073

### LINKED ISSUE #1073: Better error for JSX without spaces
From discord:

> So the first line compiles, but the second does not:
> `<li> <a>(ReactRe.stringToElement item)</a></li>`
> `<li><a>(ReactRe.stringToElement item)</a></li>`

Can we warn this better?

### PR DESCRIPTION
**Pull request by chenglou**
This error code seems very low. Is this the correct thing to do?

### CODE REVIEW

**Comment by SanderSpies** [comment]
Can you check if this error also occurs when not correctly ending a JSX tag?

**Comment by chenglou** [comment]
@SanderSpies you mean like `<li> <foo /></li>`? That one parses.

**Comment by SanderSpies** [comment]
More like `let a = <Foo bar;`.

**Comment by chenglou** [comment]
Yeah that triggers this error too. Hummm...

**Pull request closed without merging**
