### PR TITLE
Format `Js.t {. foo: bar}` to `{. "foo": bar}`

### PR DESCRIPTION
**Pull request by IwanKaramazow**
Implements string key sugar for Bucklescript Js.t object types
https://github.com/facebook/reason/issues/1404

```
/* before */
Js.t {. foo: bar}
Js.t {.. baz: boo}

/* after */
{. "foo": bar}
{.. "baz": boo}
```

### CODE REVIEW

**Comment by chenglou** [comment]
Woohoo! Just in case:

- This still supports `Js.t {. foo: bar}` fine right?
- Are the locations good? That's been a frequent problem

**Comment by IwanKaramazow** [comment]
1. `Js.t {. foo: bar}` is still supported, it'll refmt™ to `{. "foo": bar}`. And `{. "foo": bar}` will be parsed as `Js.t {. foo: bar}` which will then refmt back to `{. "foo": bar}`.
2. Let me double check locations, they can be improved.

**Comment by IwanKaramazow** [comment]
Improvement two things:
- Supports trailing commas 🤗
- Improvement location, they're as accurate as they can get:
```reason
/* jsob2.re */
type x = {. "foo": bar, "baz": hey};

/* corresponding ast with locations */
[
  structure_item (jsobj2.re[1,0+0]..[1,0+36])
    Pstr_type Rec
    [
      type_declaration "x" (jsobj2.re[1,0+5]..[1,0+6]) (jsobj2.re[1,0+0]..[1,0+35])
        ptype_params =
          []
        ptype_cstrs =
          []
        ptype_kind =
          Ptype_abstract
        ptype_private = Public
        ptype_manifest =
          Some
            core_type (jsobj2.re[1,0+9]..[1,0+35])
              Ptyp_constr "Js.t" (jsobj2.re[1,0+9]..[1,0+35])
              [
                core_type (jsobj2.re[1,0+9]..[1,0+35])
                  Ptyp_object Closed
                    method foo
                      core_type (jsobj2.re[1,0+19]..[1,0+22])
                        Ptyp_constr "bar" (jsobj2.re[1,0+19]..[1,0+22])
                        []
                    method baz
                      core_type (jsobj2.re[1,0+31]..[1,0+34])
                        Ptyp_constr "hey" (jsobj2.re[1,0+31]..[1,0+34])
                        []
              ]
    ]
]
```
I think it's ready.

**Comment by chenglou** [comment]
For a moment I thought you make it print with a trailing comma when formatting to multiple lines. One can always dream...

Thanks!

**Pull request merged**
