### PR TITLE
[atom-reason] Linux support

### PR DESCRIPTION
**Pull request by chenglou**
See comments on https://github.com/chenglou/atom-reason-loader/commit/7c91672670efe84a0a170adeb9276709e4146548

Big thanks to @vramana for helping me debug this =)

### CODE REVIEW

**Comment by chenglou** [comment]
**Don't merge yet!**

**Comment by jordwalke** [comment]
So to confirm, does this make anything worse on Mac, for recent Atom versions? Does it make it better on Linux? If the answer to both is yes, shouldn't we merge?

Also, the long term fix is to set environment variables from the project sandbox, which doesn't rely on loading the environment/PATH from the user's shell, so long term this won't be an issue. Cc @yunxing

**Comment by vramana** [comment]
[This](https://github.com/ioquatix/script-runner/blob/v1.5.0/lib/script-runner.coffee#L45-L63) looks like a possible fix as described [here](https://discuss.atom.io/t/atom-command-doesnt-pass-environment-variables-to-atom/1596/6)

**Comment by chenglou** [comment]
Closed in favor of #699

**Pull request closed without merging**
