### PR TITLE
Remove parens for negative int and float literals

### PR DESCRIPTION
**Pull request by yunxing**
This diff removes parens for negative int and float literals by lexing them as one token directly instead of rely on the parser (otherwise it won't be lookahead 1).

### CODE REVIEW

**Comment by yunxing** [comment]
@jordwalke @let-def Need some help in review here to make sure I'm not doing anything crazy.

**Comment by yunxing** [comment]
#988

**Comment by tekknolagi** [comment]
How does this work with, say, `myFunc 3 -4`, those being separate arguments? One argument?

**Comment by yunxing** [comment]
@tekknolagi I think you need a myFunc (3 -4) to represent a single expression as argument.

**Comment by yunxing** [comment]
Actually, I think this doesn't work. It makes people confuse about `foo -4` (are you applying `foo` over `-4`, or are you subtracting `foo` by `4`)? 

We can always say `-4` means negative 4 instead of subtracting 4 from something, but I would rather not do that here as it is counterintuitive for people coming from other languages. 

Note that we won't have this issue if we move to the parens function application syntax, where we can say "foo(-4)" to represent applying `foo` over `-4`.

**Comment by tekknolagi** [comment]
I think this is vaguely reminiscent of the C parsing weirdness, where if you have something like this:

```c
foo * myvar;
```

the parser does not know what kind of expression that is unless it knows the kind of symbol `foo` is. Is it a type? Another variable?

**Pull request closed without merging**
