### PR TITLE
Fix operator swap for type declarations

### LINKED ISSUE #2341: Reason reserved words are not translated in type names coming from OCaml
If you have an OCaml module which uses a Reason reserved word as a type name there is no way to access that type name from within Reason code.  For example, the `pub` type here couldn't be referenced from Reason:
```ocaml
type pub = { x : int }
```
For values, this is handled by adding a trailing `_` to the value's name.  We should have the same transformation for types.  And probably record fields, method names and anything else which could conflict if they're not translated yet.

### PR DESCRIPTION
**Pull request by anmonteiro**
Fixes #2341

### CODE REVIEW

**Comment by jordwalke** [comment]
Is this a breaking change in any way that you can think of? (For example if someone relied on accessing a `pub_` identifier in from an ocaml module).

**Comment by jordwalke** [comment]
I think this needs a little rebase. Thanks!

**Comment by anmonteiro** [comment]
I _think_ it's not a breaking change. If somebody used `pub_` in a Reason file I think it wouldn't work in the OCaml AST? I'm unsure.

Rebased!

**Comment by jordwalke** [comment]
Thank you!

**Comment by jordwalke** [comment]
I think this came up with values being named `pub`, and people using them from an ML authored library. When we fixed it, something did break in one library but we worked with that author to fix it by having them export the same value with `let pub = ` and `let pub_ = `. If it comes up with types, we can take a similar approach because this diff fixes a bug that people could have been relying on.

**Pull request merged**
