### PR TITLE
Add syntax sugar for let z = M.(a, b)

### PR DESCRIPTION
**Pull request by yunxing**
@chenglou

### CODE REVIEW

**Comment by chenglou** [comment]
Since this is constrained to module open, any chance to have some punning here? Not in this diff, but just as a general idea: `let (a, b) = MyModule`. Not too sure it's a good idea though...

Will leave @jordwalke to check this.

**Comment by yunxing** [comment]
@chenglou hmm, the punning looks not very intuitive as we are eliding stuff that are too faraway from each other.

**Comment by chenglou** [comment]
Yeah forget about that for now.

**Comment by jordwalke** [comment]
Nice catch. I didn't know we forgot to support this.

**Pull request merged**
