### PR TITLE
Fix comment for partitionAttributes to mention jsxAttrs

### PR DESCRIPTION
**Pull request by ngzhian**
Simple fix for an outdated code comment

### CODE REVIEW

**Comment by yunxing** [comment]
Looks nice, thank you!

**Comment by yunxing** [comment]
@ngzhian Do you mind sign the CLA please?

**Comment by ngzhian** [comment]
@yunxing I have already signed this for my previous PR #944, would you like me to email cla@fb.com?

**Comment by yunxing** [comment]
@ngzhian nvm then 👍 I think it is a bug in our bot. Will report internally.

**Pull request merged**
