### PR TITLE
Add version number to refmt --version output

### PR DESCRIPTION
**Pull request by tekknolagi**
Fix https://github.com/facebook/reason/issues/976

### CODE REVIEW

**Comment by yunxing** [comment]
Looks pretty good. Thanks for doing this so quickly! 

@chenglou Now I feel you should get ice cream for Max instead for me.

**Comment by tekknolagi** [comment]
@yunxing there was ice cream involved??

**Comment by tekknolagi** [comment]
Should I have committed `package.ml`?

**Comment by yunxing** [comment]
@tekknolagi Yes, you need to commit package.ml.

**Comment by yunxing** [comment]
I feel it is pointless to wait 10 hours for CI :( We should look into Circle CI. 

Merging this first. If it breaks I believe we can fix them under 10 hours.

**Pull request merged**
