### PR TITLE
Docs into master

### PR DESCRIPTION
**Pull request by vramana**
Since Github Pages can be [generated][url] from master branch's docs folder, I am submitting this PR.  The main advantage of this is 
> This lets you maintain documentation and code together on one branch, and open source maintainers can accept contributions for both in a single pull request.

It seems to build correctly. Check [here][reason] 

[reason]: https://vramana.github.io/reason/
[url]:  https://github.com/blog/2228-simpler-github-pages-publishing

### CODE REVIEW

**Comment by chenglou** [comment]
woah 61 commits

**Comment by vramana** [comment]
I wanted to preseve the history of the files in the master branch. Although the github doesn't show it. You can track the history by looking that parent commits. If you think history isn't so important, then I can squash them.

**Comment by chenglou** [comment]
Yeah I think erasing history here is fine. cc @jordwalke

**Comment by vramana** [comment]
@chenglou Updated the PR

**Comment by chenglou** [comment]
@vramana what's the second point [here](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch) about?

"your repository must not follow the repository naming scheme `<username>.github.io` or `<orgname>.github.io`"

Also, can you add an `.npmignore` to the root and ignore `docs/`?

**Comment by vramana** [comment]
@chenglou They are telling the repo name can't be `facebook.github.io`. 

> Also, can you add an .npmignore to the root and ignore docs/?

Yes. I will do that

**Comment by jordwalke** [comment]
Will this make it so jQuery is returned in git grep and github search?

**Comment by vramana** [comment]
@jordwalke It seems so.

**Comment by jordwalke** [comment]
I think you can fix that with a simple .gitattributes file. Want to see if that will work? Thanks for sending this PR!

**Comment by jordwalke** [comment]
Why is CI so slow?

**Comment by chenglou** [comment]
The whole Facebook organization shares the same travis limit I think. So we're queuing behind other facebook/ projects. Faster at night.

**Comment by vramana** [comment]
@jordwalke I didn't get you. I have never used gitattributes in the past.

**Comment by chenglou** [comment]
@vramana see my comment. `.gitattributes` specifies which file (or globs) are supposed to be treated as binary. These receive special treatment, including not being displayed in the diff view when they change, and probably not being indexed by github search.

**Comment by vramana** [comment]
@chenglou Seems like I missed your previous comment. Which files should I mark at binary? All the vendor files?

**Comment by vramana** [comment]
Also do we need to keep the examples folder? It seems completely unrelated.

**Comment by vramana** [comment]
How to mark a folder recursively as binary in gitattributes? Currently I supress all jQuery mentions from invidually target the folders. But I don't think it's ideal.

**Comment by jordwalke** [comment]
Does double star `**` work?

**Comment by vramana** [comment]
@jordwalke It does. What else work is pending in this PR?

**Comment by jordwalke** [comment]
I think this is good to commit now. We may have to revert (or find the right fix) if jQuery ends up showing up in searches.

**Comment by vramana** [comment]
@jordwalke I have checked from git grep. It doesn't show up.

**Comment by jordwalke** [comment]
@chenglou What else do we have to do? Do we just merge this and then delete the docs branch or can we keep it around?

**Comment by chenglou** [comment]
`.npmignore`, `.gitattributes`, can't think of anything else. I think we're good merging this =)

**Comment by chenglou** [comment]
Seems working. Lemme test by making changes to the new master docs.

**Comment by chenglou** [comment]
Alright, coordinated with the internal folks to make the change! Thanks @vramana! =D

**Comment by jordwalke** [comment]
thanks!

**Pull request merged**
