### PR TITLE
Print functions as javascript

### PR DESCRIPTION
**Pull request by IwanKaramazow**
https://github.com/facebook/reason/issues/1442

```reason
/* before */
let foo (bar) = 1;
let myObj = {pub p () = 10};

/* after */
let foo = (bar) => 1;
let myObj = {pub p = () => 10};
```

### CODE REVIEW

**Comment by chenglou** [comment]
Should we do the same for functors?

**Comment by IwanKaramazow** [comment]
Yes, we should, since they're "functions" over modules.

Still struggling with a idempotency problem at the moment with functors.

```bash
Iwans-MBP:reason Iwan$ cat functor.ml
module Increment (M : X_int) : X_int = struct
    let x = M.x + 1
  end;;
Iwans-MBP:reason Iwan$ ./refmt_impl.native --parse ml --print re functor.ml
module Increment = (M: X_int) : X_int => {
  let x = M.x + 1;
};
Iwans-MBP:reason Iwan$ ./refmt_impl.native --parse ml --print re functor.ml | ./refmt_impl.native --parse re --print re
File "", line 1, characters 30-31:
Error: 2149: <UNKNOWN SYNTAX ERROR>
```

```reason
/* valid parse */
module Increment = (M: X_int) => {
  let x = M.x + 1;
};

/* invalid parse */
module Increment = (M: X_int) : X_int => {
  let x = M.x + 1;
};
```

**Comment by chenglou** [comment]
Aaah, is this related to https://github.com/facebook/reason/pull/1409?

**Comment by IwanKaramazow** [comment]
it might be, parser looks pretty ok...
```reason
/* valid parse... */
module Increment  (M: X_int) :X_int {
  let x = M.x + 1;
};
```
Time to call the cavalry?

**Comment by chenglou** [comment]
cc @let-def 

I'm merging this as-is for now then. Let's fix the functor printing and parsing #1472.

Thanks!

**Pull request merged**
