### PR TITLE
JSX string literal

### PR DESCRIPTION
**Pull request by cristianoc**
Special case string literals in JSX so ReasonReact.string is added automatically.

### CODE REVIEW

**Comment by IwanKaramazow** [comment]
This raises another natural question, what happens with floats, ints, lists and arrays?
Since their "type" can be determined at lex-time and compiled with a ppx, do we still want the conversion for those others?

**Comment by wegry** [comment]
@IwanKaramazow wouldn't it make sense that if we aren't sure about conversions, we stick with vanilla React's behavior, i.e. only strings are valid and not floats, ints, list, and arrays?

**Comment by rickyvetter** [comment]
There are some pretty serious problems that come with this because ppx doesn't have access to the type information. It doesn't allow strings to be lifted outside of the ppx in a typesafe manner which will almost certainly result in issues with refactoring and some really confusing bugs for newcomers.

As an example:

```js
<div> "foo" </div>
```
will typecheck and
```js
let foo = "foo";
<div> foo </foo>
```
will not.

**Comment by gilbert** [comment]
I think the string literal lifting issue is a small price to pay and should not be considered a deal breaker.

**Comment by rickyvetter** [comment]
@gilbert it's not just lifting that will cause issues:

```js
<div> {"Hello, " ++ name} </div>
```
won't typecheck and
```js
<div> {localize("Title of the Page")} </div>
```
won't typecheck unless localize only works as a React element. You'll need a different function to operate outside of React.

If everyone were very familiar with these nuances then sure, I think this would be fine for convenience. What I'm worried about is how to explain this differing behavior to people who aren't aware of the nuances.

**Comment by gilbert** [comment]
I see, thanks for showing the other issues.

**Comment by kujon** [comment]
> It doesn't allow strings to be lifted outside of the ppx in a typesafe manner which will almost certainly result in issues with refactoring and some really confusing bugs for newcomers.

TypeScript has got a very similar behaviour when using type guards. It's the most annoying thing in the world, because it makes you re-factor code only because the compiler doesn't understand.

Let's not go there with Reason please.

**Comment by kennetpostigo** [comment]
@rickyvetter I wonder how that would work for people using bs-react-native? They could probably alias it?

**Comment by rickyvetter** [comment]
Yeah if this was a path we wanted to explore we'd work with the `bs-react-native` folks to make sure it would work for them.

**Comment by texastoland** [comment]
A text element makes sense. Alternatively what about a version of `{j|hello, $interpolation|j}` that coerces to `reactElement`? That seems less intrusive to me since a newcomer likely also wants interpolation.

**Pull request closed without merging**
