### PR TITLE
fix(docs): Updating README.md

### PR DESCRIPTION
**Pull request by iamdarshshah**
### Changes

- [x] Added Reason logo

- [x] Aligning header to center

### CODE REVIEW

**Comment by jordwalke** [comment]
Looks pretty great! I'm glad you got the svg so that it renders cleanly at all resolutions.

**Comment by jordwalke** [comment]
Thanks for the first contribution! Feel free to add an entry to the changes/history.md doc to include your contribution.

**Comment by iamdarshshah** [comment]
Sure, Thanks @jordwalke 👍

**Comment by iamdarshshah** [comment]
@jordwalke Should I make an entry under `3.7.0` - by adding a new title `Changes` in ./HISTORY.md doc?

**Pull request merged**
