### PR TITLE
Fix record spread with no labels.

### LINKED ISSUE #689: Invalid record spread syntax
```
{...foo};
```

This is invalid syntax. `[...bar]` works and prints as plain `bar`; for consistency, `{...foo}` should print as `foo`.

### PR DESCRIPTION
**Pull request by pvolok**
Fix #689

### CODE REVIEW

**Comment by yunxing** [comment]
Looks great, thanks!

**Comment by chenglou** [comment]
What happens when there's a single mutable field?

**Comment by jordwalke** [comment]
It appears to give a compiler error because record fields cannot have zero fields extended.

```
Reason # let x = {contents: 10};
let x : ref int = {contents : 10}                                                                                                                                                                                                                                               Reason # x.contents = 100;
- : unit = ()                                                                                                                                                                                                                                                                   Reason # x;
- : ref int = {contents : 100}                                                                                                                                                                                                                                                  Reason # let y = {...x};
Error: broken invariant in parsetree: Records cannot be empty.
```

**Comment by pvolok** [comment]
Forgot to test. Sorry...

I'll try to hack on ocaml.

**Comment by jordwalke** [comment]
I think the change to ocaml might be somewhat difficult since the type cannot be inferred without one label to work off of.

```rust
type t = {someField: int};
let myFun y => {...y, someField: foo};
let myFun y = {...y};
```

The first function will be inferred as `t=>t` because the record label gives enough information to work from, but the second would need to be inferred as `anyRecordType => anyRecordType`, but OCaml does not currently have any notion of "any type that is a record".

In other words, it would be neat to have this feature, but I'm not sure it will be worth the benefit (compared to other things we could be building). (Unless you already know how to implement this in the OCaml core compiler).

**Comment by jordwalke** [comment]
So I'd say this diff is fine as it is, but we could make a slightly better error message perhaps.

**Comment by pvolok** [comment]
No, I'm new to the ocaml world. So yeah, you talked me out of it for now. Hopefuly will dig it one day :)

Should we fail in the parser, but with a better message?

**Comment by yunxing** [comment]
Found some discussion about this issue before: http://caml.inria.fr/pub/ml-archives/caml-list/2005/01/9deef19c1b8dde84b81b554a7caa482e.en.html, which is basically what @jordwalke mentioned. 

I think there are two options for us now:
  1) Print `{...bar}` into `bar` -- this may confuse people as people may expecting the syntax {...bar} to make a shallow copy of `bar`. 
  2) Make a better syntax error when people write `{...bar}`.

**Comment by pvolok** [comment]
If we autoformat `{...bar}` into `bar`, it is not only confusing, but can also introduce bugs. Why would someone write `{...bar}` rather than trying to make a shallow copy?

**Comment by yunxing** [comment]
@pvolok Sorry just saw this. Maybe we here we should just provide a better syntax error here.

**Comment by jordwalke** [comment]
Agree.

**Pull request merged**
