### PR TITLE
Preserve semicolon printing in seq-expr inside jsx-children

### PR DESCRIPTION
**Pull request by IwanKaramazow**
Fixes https://github.com/facebook/reason/issues/2293

### CODE REVIEW

**Comment by bloodyowl** [comment]
it would be great if we could bump bs-platform to a minor version once this is merged, this is blocking us from upgrading at the time

cc @bobzhang

**Comment by bloodyowl** [comment]
is there anything we can do to see this PR merged and released?

**Comment by bloodyowl** [comment]
any updates blocking this? this is a quite serious bug and prevents us from upgrading

cc @jordwalke

**Comment by IwanKaramazow** [comment]
Not sure what happened when rebasing, but openend a new one in https://github.com/facebook/reason/pull/2330 (up to date in master)

**Pull request closed without merging**
