### PR TITLE
Add merlin destruct support to Atom Reason

### PR DESCRIPTION
**Pull request by SanderSpies**
Mostly works when you press `alt+p`.

Except that the pattern match isn't converted to Reason yet - it's not clear yet to me where this should happen. I also don't see it properly being converted for type information (of keyword is still there...).

### CODE REVIEW

**Comment by SanderSpies** [comment]
Related to #625.

**Comment by SanderSpies** [comment]
Needs more checks, breaks too easy currently.

**Comment by SanderSpies** [comment]
To clarify a bit more what this does, if you type the following

```
type cursor =
  | Default
  | Pointer
;

let foo bar:cursor =>
  bar
;
```

and press `alt + p` when the cursor is at `bar`, `bar` will be replaced by:
```
match (bar : cursor) with
| Default  -> failwith "TODO"
| Pointer  -> failwith "TODO"
```

(Yes, the match should be a switch - but not sure where this is being handled).

**Comment by SanderSpies** [comment]
Is `OcamlTypeToReasonType` actually being used somewhere? I can delete it and everything builds just fine... also searching finds no usages.

**Comment by chenglou** [comment]
It's supposed to be used by BetterErrors before to crawl the ocaml type errors and turn them into reason type errors.

**Comment by chenglou** [comment]
Just tried this. Pretty cool, except yeah, it prints the ocaml syntax rather than the Reason one in a reason file. cc @let-def, given that #676 got implemented without any merlin change, could it be a merlin problem here?

**Comment by jordwalke** [comment]
Whoa!

**Comment by chenglou** [comment]
"https://github.com/facebook/reason/blob/master/src/ocamlmerlin_reason.ml doesn't have pretty print hook, so it cannot work with latest merlin-extend".

More info: https://github.com/let-def/merlin-extend/commit/1e885ee0a624c9464073e727e4274e0c26e1aa8a

Leaving this here to @SanderSpies.

**Comment by jordwalke** [comment]
I'm going to try adding that pretty print hook in Reason right now. If I succeed, then this diff will work well, right?

**Comment by let-def** [comment]
I think so, if codebases didn't diverge too much. I can fix issues in the next few hours.

**Comment by SanderSpies** [comment]
Rebased this branch to the latest master version

**Comment by chenglou** [comment]
Tested locally. Works well! @jordwalke you should try it! =D

**Pull request merged**
