### PR TITLE
CI using Azure Pipelines

### PR DESCRIPTION
**Pull request by bryphe**
This sets up an initial pipeline for `esy`-enabled Reason builds.

A few additional issues:
- [x] The 4.06 build of the compiler isn't being picked up 
- [x] The `dune` being picked up by OPAM is old (1.2.1), so it doesn't recognize the dune format.

### CODE REVIEW

**Comment by bryphe** [comment]
Testing these builds on my forked repo for now: https://dev.azure.com/reasonml/reason/_build?definitionId=1&_a=summary

**Comment by kaylangan** [comment]
I'm a Program Manager for Azure Pipelines. Let me know if you have any questions or suggestions. I'm happy to help!

**Comment by jordwalke** [comment]
Is this ready to go? Anything I need to enable on our side? All the Azure pipelines are already "running" - they're just dummy pipelines right now.

**Comment by jordwalke** [comment]
Let's try this!

**Pull request merged**
