### PR TITLE
Fix utop compilation

### PR DESCRIPTION
**Pull request by cristianoc**
https://github.com/facebook/reason/issues/1278

### CODE REVIEW

**Comment by chenglou** [comment]
Feel free to self-merge

**Comment by cristianoc** [comment]
Actually tests are failing. Specifically the utop test fails when doing:
```
utop -init src/rtop_init.ml
...
Error: Reference to undefined global `Misc'
```

This happens when either of the following are run in utop:
```
#require "ocaml-migrate-parsetree";;
or
#require "reason";;
```

Somehow this happens on utop versions greater than 1.19.3.

**Comment by cristianoc** [comment]
@let-def any thoughts?

**Comment by let-def** [comment]
This unit is defined in `compiler-libs/ocamlcommon.cma`, maybe try with:
`#require "compiler-libs.common";;`.

**Comment by cristianoc** [comment]
@letdef that did not work, but this seems to wort for me:
```
#load "compiler-libs/ocamlcommon.cma"
```
wondering how reliable that is.

**Comment by let-def** [comment]
compiler-libs.common is a direct dependency of ocaml-migrate-parsetree, it would be weird if it had worked by requiring it manually...
But this dep should trigger the loading of "ocamlcommon.cma":
```
$ ocamlfind ocamlc -only-show -linkpkg -package compiler-libs.common
findlib: [WARNING] Interface topdirs.cmi occurs ...
ocamlc.opt -I /.../lib/ocaml/compiler-libs /.../lib/ocaml/compiler-libs/ocamlcommon.cma
```
That's the only purpose of compiler-libs.common package.
There is something fishy :/.

**Pull request merged**
