### PR TITLE
Add error message for error state 745

### PR DESCRIPTION
**Pull request by yunxing**
#507

Error message for invalid state after `...`

@chenglou @yawaramin

### CODE REVIEW

**Comment by chenglou** [comment]
Woah, that's it? Nice...
Is it possible to warn more precisely? E.g. "instead you've put `as`"

**Comment by yunxing** [comment]
I was thinking if we should do that or integrate it with Better_error_messages? (since you will see the original input anyway with Better_error_messages).

**Comment by chenglou** [comment]
I'd rather defer as much as possible to the compiler/parser, since not everyone will use BetterErrors. Actually, the majority won't be using it at all; hopefully they'll be staying within the editor and not needing to see any error after compilation. The earlier the warning the better.

That being said, there _is_ a  category of error messages that should definitely stay in BetterErrors-land. E.g. the ones that concerns the ecosystem, best practices, and all other moving domains:
screenshot 2016-05-22 23 13 00

**Comment by yunxing** [comment]
@chenglou Good point.

**Pull request merged**
