### PR TITLE
implement Pexp_letexception

### PR DESCRIPTION
**Pull request by IwanKaramazow**
https://github.com/facebook/reason/issues/1424

Adds support for `Pexp_letexception`.

Ocaml:
```ocaml
let () = let exception E in raise E

```
resulting in parse tree:
```

(* parse tree *)
[
  structure_item (exc.ml[1,0+0]..[1,0+35])
    Pstr_value Nonrec
    [
      <def>
        pattern (exc.ml[1,0+4]..[1,0+6])
          Ppat_construct "()" (exc.ml[1,0+4]..[1,0+6])
          None
        expression (exc.ml[1,0+9]..[1,0+35])
          Pexp_letexception
          extension_constructor (exc.ml[1,0+23]..[1,0+24])
            pext_name = "E"
            pext_kind =
              Pext_decl
                []
                None
          expression (exc.ml[1,0+28]..[1,0+35])
            Pexp_apply
            expression (exc.ml[1,0+28]..[1,0+33])
              Pexp_ident "raise" (exc.ml[1,0+28]..[1,0+33])
            [
              <arg>
              Nolabel
                expression (exc.ml[1,0+34]..[1,0+35])
                  Pexp_construct "E" (exc.ml[1,0+34]..[1,0+35])
                  None
            ]
    ]
]
```

Becomes in Reason:
```reason
let () = {
  exception E;
  raise(E);
};
```
resulting in parse tree:
```
[
  structure_item (local.re[1,0+0]..[4,39+2])
    Pstr_value Nonrec
    [
      <def>
        pattern (local.re[1,0+4]..[1,0+6])
          Ppat_construct "()" (local.re[1,0+4]..[1,0+6])
          None
        expression (local.re[1,0+9]..[4,39+1])
          Pexp_letexception
          extension_constructor (local.re[2,11+12]..[2,11+13])
            pext_name = "E"
            pext_kind =
              Pext_decl
                []
                None
          expression (local.re[3,26+2]..[3,26+11])
            Pexp_apply
            expression (local.re[3,26+2]..[3,26+7])
              Pexp_ident "raise" (local.re[3,26+2]..[3,26+7])
            [
              <arg>
              Nolabel
                expression (local.re[3,26+8]..[3,26+9])
                  Pexp_construct "E" (local.re[3,26+8]..[3,26+9])
                  None
            ]
    ]
]
```

### CODE REVIEW

**Comment by chenglou** [comment]
Ooooh boy, might need to temporary remove the test for this one because of 4.02... sigh

**Comment by IwanKaramazow** [comment]
Do we have a way of saying "only test this stuff on 4.04 and above"?

**Comment by chenglou** [comment]
The script for testing is `test-with-version.sh`. You can tweak things there, etc. But might not be worth it for now. We can come back to this after we ship

**Comment by chenglou** [comment]
👍

**Pull request merged**
