### PR TITLE
Fix identation of JSX record attributes

### PR DESCRIPTION
**Pull request by IwanKaramazow**
https://github.com/facebook/reason/issues/848

Before:
```reason
let w =
    <Window
      style={
              ...LayoutSupport.defaultStyle,
              marginTop: 20,
              width: state.width,
              height: 400,
              paddingTop: 100,
              paddingBottom: 100,
              paddingLeft: 100,
              paddingRight: 100,
              justifyContent: CssJustifySpaceBetween,
              flexDirection: CssFlexDirectionRow
            }
      onKey=(updater handleInput)
    />
```
After:
```reason
let w =
  <Window
    style={
      ...LayoutSupport.defaultStyle,
      marginTop: 20,
      width: state.width,
      height: 400,
      paddingTop: 100,
      paddingBottom: 100,
      paddingLeft: 100,
      paddingRight: 100,
      justifyContent: CssJustifySpaceBetween,
      flexDirection: CssFlexDirectionRow
    }
    onKey=(updater handleInput)
  />;
```

### CODE REVIEW

**Comment by chenglou** [comment]
RAGE MERGE

**Comment by SanderSpies** [comment]
This is so hot.

**Comment by jordwalke** [comment]
As always. Thank you!

**Comment by jordwalke** [comment]
"Rage merge" lol

**Pull request merged**
