### PR TITLE
[Docs] missing backslash in Reason translation of /*

### PR DESCRIPTION
**Pull request by anmonteiro**

### CODE REVIEW

**Comment by tekknolagi** [comment]
Why does it need additional slashes?

**Comment by anmonteiro** [comment]
to render the HTML properly. this is a simple typo, other examples also have them

**Comment by tekknolagi** [comment]
When I tested your diff, it rendered incorrectly in my browser, but the original renders just fine.

**Comment by anmonteiro** [comment]
There might be a misunderstanding here. What is incorrectly for you?

I expect it to render `/\*`, but the current live website is rendering `/*`.

**Comment by chenglou** [comment]
Yeah this is right. Thanks!

**Pull request merged**
