### PR TITLE
Remove string quotes checking inside comments

### PR DESCRIPTION
**Pull request by yunxing**
#660

### CODE REVIEW

**Comment by jordwalke** [comment]
Will this fail to parse if you convert this back to OCaml syntax (assuming you can preserve comments?)

**Comment by jordwalke** [comment]
I wish this could still be checked but changed to a warning which could be suppressed.

**Comment by yunxing** [comment]
@jordwalke You are right, this is not compatible with the original OCaml parser.

**Comment by yunxing** [comment]
abandoning this as it won't be compatible with ocaml.

**Pull request closed without merging**
