### PR TITLE
[atom-reason] Fix nuclide type hint squashed layout

### LINKED ISSUE #663: Type hints display error in Atom
I used atom to read the code of Infer, and it shows as:
screen shot 2016-08-08 at 5 36 56 pm

My packages:
screen shot 2016-08-08 at 5 38 34 pm

### PR DESCRIPTION
**Pull request by chenglou**
See issue https://github.com/facebook/nuclide/issues/659#issuecomment-238198585
Fixes #663

Not sure how it acts on atom 1.8 though.

### CODE REVIEW

**Comment by pvolok** [comment]
Did you forget to uncomment css rules and require `fix-nuclide.less`?

**Comment by chenglou** [comment]
...*facepalm* I commented out this style instead of the one in my style sheet.

**Comment by chenglou** [comment]
I think Infer is on Atom 1.8. Atom will auto-upgrade to 1.9 anyway. Pinging @cristianoc just in case this somehow breaks 1.8 though.

**Comment by cristianoc** [comment]
@chenglou merge away.

**Pull request merged**
