### PR TITLE
Remove utop

### PR DESCRIPTION
**Pull request by chenglou**

### CODE REVIEW

**Comment by chenglou** [comment]
@yunxing does this look legit?

**Comment by jordwalke** [comment]
@chenglou Have you tested the `rtop` repo that you made to replace this?

https://github.com/reasonml/rtop

**Comment by tekknolagi** [comment]
@chenglou Is there any movement on this?

**Comment by chenglou** [comment]
Jordan wanted https://github.com/reasonml/rtop not to be a fork of this repo. I dunno how much time it'll take. Feel free to take this over

**Comment by jordwalke** [comment]
Would really appreciate this @tekknolagi. Now that the 4.03+ diff is in it's a good time to reorg the repo into several smaller packages

**Comment by tekknolagi** [comment]
I can start on this as soon as https://github.com/facebook/reason/pull/1113 lands.

**Comment by chenglou** [comment]
Closed in favor of #1372

**Pull request closed without merging**
