### PR TITLE
Add filetype directive

### PR DESCRIPTION
**Pull request by mjackson**

### CODE REVIEW

**Comment by jordwalke** [comment]
Thanks! Will merge once CI passes

**Comment by mjackson** [comment]
FWIW syntax highlighting works correctly when I put the VimReason snippet *before* the Vundle stuff in my `.vimrc`.

**Comment by chenglou** [comment]
Seems like Jordan added something that made this diverge

**Comment by mjackson** [comment]
Ya, we don't need to have this. It was an issue with the way Vim loads plugins. vim-reason-loader should address this.

**Pull request closed without merging**
