### PR TITLE
Remove rebuild hack

### PR DESCRIPTION
**Pull request by yunxing**
We had a lot of hacks into rebuild so that we could statically link our
custom ocamlbuild rules into rebuild. It was a pain to maintain and debug.

Max and I found a much less hacky approach to link the custom rules defined
in reasonbuild.ml:

1. Move reasonbuild.ml into a tmp directory, call it myocamlbuild.ml
2. Run ocamlbuild with '-just-plugin' option in that directory
3. Step 2 will generate a binary called "myocamlbuild", rename it and ship it
as "rebuild"

After step 3, 'rebuild' can now be used as an augmented 'ocamlbuild' with custom rules.

### CODE REVIEW

**Comment by jordwalke** [comment]
Will this approach play with projects that already have their own myocamlbuild? Will it union the two rules?

**Comment by tekknolagi** [comment]
@jordwalke it looks like yes, this is basically the same as old workflow.

**Comment by yunxing** [comment]
@jordwalke Yes. This prebuilds the augmented version of ocamlbuild in a temp directory when installing reason itself. It doesn't conflict with myocamlbuild.ml

**Comment by yunxing** [comment]
Less hack and better engineering!

**Pull request merged**
