### PR TITLE
Vendor cmdliner in

### PR DESCRIPTION
**Pull request by yunxing**
RIP package management

### CODE REVIEW

**Comment by yunxing** [comment]
@bobzhang ^

**Comment by chenglou** [comment]
We'll do whatever that makes @bobzhang's bspack workflow a bit easier. But for the sake of sharing cached artifacts in the future we should probably pull these out again or something...

**Comment by bobzhang** [comment]
bspack is done in dev time, git submodules will be good enough

**Comment by chenglou** [comment]
Is it possible for bspack to work on npm installed cmdliner?

**Pull request merged**
