### PR TITLE
parse and print attributes on object type rows

### PR DESCRIPTION
**Pull request by IwanKaramazow**
Fixes https://github.com/facebook/reason/issues/1635

### CODE REVIEW

**Comment by chenglou** [comment]
Too bad the attribute can carry more info like `[@@bs.set no_get]`. Otherwise we can have `{mutable "foo": bar}`. cc @bobzhang

**Comment by bobzhang** [comment]
Do you find set only attributes useful?

**Comment by chenglou** [comment]
Haven't used any of these much yet

**Comment by chenglou** [comment]
Aaaalright, is this ready?

**Comment by IwanKaramazow** [comment]
Ready 🙌

**Comment by chenglou** [comment]
Good stuff

**Pull request merged**
