### PR TITLE
More helpful syntax error for trailing semicolon in record

### LINKED ISSUE #1967: [Suggestion] JSX semicolon - more helpful Syntax Error
For some syntax errors I get a message `[merlin] A syntax error occurred. Help to improve this message:`.

For example when I put an extra `;` at the end of `</div>;` :

```reason
let make = (_children) => {
  ...component,
  render: _self => <div> 5 </div>;
};
```

screen shot 2018-05-28 at 7 37 11

Perhaps a more specific error message can be shown
(moved from https://github.com/reasonml-editor/vscode-reasonml/issues/217)

### PR DESCRIPTION
**Pull request by anmonteiro**
Fixes #1967 in the same style of #1925

### CODE REVIEW

**Comment by anmonteiro** [comment]
Agreed, I'll work that in

**Comment by anmonteiro** [comment]
@IwanKaramazow fixed the code such that it gives helpful error messages for all these cases:

```reason
let make = (_children) => {
  ...component,
  render: _self => <div> 5 </div>;
};

let make = (_children) => {
  ...component;
};

let make = (_children) => {
  ...component;
  render: _self => <div> 5 </div>
}                                       ;

```

**Comment by anmonteiro** [comment]
all record cases now covered with the addition of the following:

```reason
let make = (_children) => {
  foo: bar;
}                                       ;

let make = (_children) => {
  foo: bar;
  render: _self => <div> 5 </div>
}                                       ;

let make = (_children) => {
  foo: bar,
  baz: qux;
  render: _self => <div> 5 </div>
}                                       ;

let make = (_children) => {
  foo: bar,
  foozy: bary,
  baz: qux;
  render: _self => <div> 5 </div>
}                                       ;

```

**Comment by chenglou** [comment]
Thanks! Tweaked the message to be shorter

**Pull request merged**
