### PR TITLE
Less verbose printing of first class modules in constraint patterns

### PR DESCRIPTION
**Pull request by IwanKaramazow**
Fixes https://github.com/facebook/reason/issues/1942

### CODE REVIEW

**Comment by hcarty** [comment]
Thank you!

**Comment by jordwalke** [comment]
This is great! Are the first parens necessary around `(module F)`?

**Comment by IwanKaramazow** [comment]
No I don't think they are needed, but I'm "restructuring some Menhir rules" to make this work. Just a few conflicts left, the puzzle is almost complete. 😃

**Comment by hcarty** [comment]
😀👍🎊🐫

**Pull request merged**
