### PR TITLE
Upgrade the docs to reflect that Rebel's Bucklescript integration now works.

### PR DESCRIPTION
**Pull request by gerred**
This is a small change, but per the Discord it seems the Rebel + BuckleScript integration is working now. Just updating to match!

### CODE REVIEW

**Comment by gerred** [comment]
CLA signed.

**Comment by Schmavery** [comment]
Afaik, it also currently generates .merlin files (a few lines under your change it says that feature is coming soon)

**Comment by gerred** [comment]
@Schmavery I'll add that change now!

**Comment by yunxing** [comment]
Haven't been following BS + rebel closely. @chenglou Would you mind take a look at this PR?

**Comment by chenglou** [comment]
Yeah it is working. Thanks!

**Pull request merged**
