### PR TITLE
Including more of the recent deps in bspack workflow

### PR DESCRIPTION
**Pull request by chenglou**
@tekknolagi

### CODE REVIEW

**Comment by chenglou** [comment]
ok @tekknolagi this works, after following https://github.com/facebook/reason/issues/1156#issuecomment-288009930
Guess what the new error is though!

```
File "ppx_deriving.ml", line 105, characters 8-12:
Uninterpreted extension 'expr'.
```

Time to macroexpand this? I'm fine doing this at build time rather than pre-expanding them

**Comment by tekknolagi** [comment]
@chenglou I'd rather expand at build-time, yes. We can use the `-ppx` flag.

**Comment by tekknolagi** [comment]
What if, instead of sed, we just mock the `Result` module?

**Comment by chenglou** [comment]
migrate_parsetree_ast_io.ml and migrate_parsetree_ast_io.mli assume > 4.02. We can just qualify these with `Result.result` in that repo and that should do the trick.

**Comment by tekknolagi** [comment]
Rebased on master.

**Comment by chenglou** [comment]
@let-def Sorry, we're a bit blocked on this one and don't know how to proceed. Do you know what's the error here?

```
File "reason_parser.ml", line 5, characters 2-42:
Error: Unbound value MenhirLib.StaticVersion.require_20160825
```

**Comment by let-def** [comment]
This happens if the parser was not generated by the same version of menhir as the one installed. Is that possible?
In that case, it might be possible to bundle menhirlib version (if you embed the parser, then you should also embed the corresponding menhirLib).

**Comment by let-def** [comment]
(MenhirLib is licensed under LGPL2)

**Comment by chenglou** [comment]
@yunxing pushed our latest changes, can you se if you can repro this:

```
File "refmt_main.ml", line 1:
Error: No implementations provided for the following modules:
         Parsetree referenced from refmt_main.cmx
         Asttypes referenced from refmt_main.cmx
```

Note the installation requirements at the top of the file. Thanks.

**Comment by chenglou** [comment]
New instructions out at https://github.com/facebook/reason/commit/575feb86bf1c780085cf1f7a54b951dd06a2f7ed

> The compiler pipeline discards the output of ppx

bspack works on source files and doesn't support ppx. For now we'll trail one version behind and get the artifacts of reason from `npm install -g reason-cli` (which itself uses opam under the hood), pack them, and do whatever with them.

Hopefully one day we'll be able to pack the repo and put the workflow under CI or something. This way `npm install reason` would just compile a few big reason source files: refmt, reactjs_jsx_ppx, refmttype, and ocamlmerlin-reason (currently not possible to pack?). No need to emulate opam with the npm install flow.

**Pull request closed without merging**
