### PR TITLE
interleave whitespace between recursive let and module bindings

### PR DESCRIPTION
**Pull request by IwanKaramazow**
Fixes https://github.com/facebook/reason/issues/1958

### CODE REVIEW

**Comment by chenglou** [comment]
Should we even allow whitespace between recursive let bindings? As much as possible I'd still like us to be opinionated on whitespace

**Comment by IwanKaramazow** [comment]
I think we should for consistency, it would be a little bit weird if we didn't allow it here.
Imagine rewriting the Reason printer with recursive functions instead of using the object system:
```
let rec printExpression = (e) => beatifulPrinting(e)

and printPattern = (pat) => ...

and printModule = (m) => ...
```
Some space between the different bindings gives a little more room to breath

**Comment by chenglou** [comment]
Would this actually happen though? Because the reality would be:

```reason
let rec printExpression = (e) => {
  beatifulPrinting(e)
  ...
}
and printPattern = (pat) => {
  ...
}
and printModule = (m) => {
   ...
}
```

Right?

**Comment by IwanKaramazow** [comment]
Yes, but someone might want the right the following:
```reason
let rec main = (e) => {
  ...
}

and helper1 = (_) => {
  ...
}
and helper2 = (_) => {
   ...
}
and helper3 = (_) => {
   ...
}
```
`helper1`, `helper2`, `helper3` could be grouped together. Visually it becomes very clear that what the relation between the `helper{X}` and `main` is.

I might be completely wrong though, no opinion, and can close the PR.

**Comment by jaredly** [comment]
I have a mild preference for keeping recursive bindings together

**Pull request merged**
