### PR TITLE
OCaml 4.06.0 support

### PR DESCRIPTION
**Pull request by ncihnegn**
Code copied from OCaml 4.06.0

#1608

### CODE REVIEW

**Comment by jordwalke** [comment]
Thanks! It looks like it's failing on (at least) 4.04 with "Location.deprecated" not being found.

**Comment by ncihnegn** [comment]
Not sure how to make it work for pre-4.06 versions. It is due to Warnings.Deprecated type change.

**Comment by chenglou** [comment]
cc @hcarty

**Comment by rgrinberg** [comment]
Using cppo comes to mind...

**Comment by jordwalke** [comment]
Note that if you rebase, you'd pick up some commented code from OCaml that I copy/pasted into the repo, which would be useful for making the tests pass on all OCaml versions perhaps. I'm looking to add 4.06 support myself, so if there's anything else I can do to help, please feel free to reach out to me on Discord and I can help get this through.

**Comment by jordwalke** [comment]
Is there a reason why you bumped the menhir version?

**Comment by ncihnegn** [comment]
Just want to use the latest. My bad. I will refrain from adding unrelated commits.

**Comment by hcarty** [comment]
If it works with the latest menhir then it's probably worth reflecting that in the version constraints.

**Comment by jordwalke** [comment]
I've made this work with all ocaml compiler versions in [this pr](https://github.com/facebook/reason/pull/1663) and I actually had to eventually bump menhir as you have in this diff. Thank you!

**Pull request closed without merging**
